---
include:
  - project: 'youniqx/infrastructure/ci-commons'
    ref: v1.87.178
    file: 'global.yaml'
  - component: $CI_SERVER_FQDN/youniqx/mia/ci-templates/disable-ltex@main

pages:
  tags: [linux-unprivileged]
  variables:
    KUBERNETES_MEMORY_REQUEST: 20Gi
    KUBERNETES_MEMORY_LIMIT: 20Gi
  stage: deploy
  image: harbor.youniqx.com/youniqx-cloud-infrastructure/youniqx/mia/android-build:1.11.14
  script:
    - gradle composeApp:wasmJsBrowserDistribution
    - mkdir -p public && cp -R ./composeApp/build/dist/wasmJs/productionExecutable/* ./public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
