---
include:
  - project: 'youniqx/infrastructure/ci-commons'
    ref: v1.89.11
    file: 'global.yaml'
  - project: 'youniqx/infrastructure/ci-commons'
    ref: v1.89.11
    file: 'release.yaml'
  - local: 'gitlab/sbom.yml'
  - component: $CI_SERVER_FQDN/youniqx/mia/ci-templates/disable-ltex@main

default:
  retry: 2

variables:
  VAULT_SERVER_URL: https://vault.build.youniqx.cloud
  VAULT_AUTH_ROLE: youniqx_mobile_chapter_time_unprotected
  VERSION_CODE: ${CI_PIPELINE_ID}
  # renovate: datasource=gitlab-releases depName=gitlab-org/cli extractVersion=^v(?<version>.*)$ registryUrl=https://gitlab.com
  GLAB_VERSION: 1.80.4


pages:
  tags: [linux-unprivileged]
  variables:
    KUBERNETES_MEMORY_REQUEST: 20Gi
    KUBERNETES_MEMORY_LIMIT: 20Gi
  stage: deploy
  image: harbor.youniqx.com/youniqx-cloud-infrastructure/youniqx/mia/android-build:1.14.6
  script:
    - gradle composeApp:wasmJsBrowserDistribution
    - mkdir -p public && cp -R ./composeApp/build/dist/wasmJs/productionExecutable/* ./public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


release-test:
  extends: .release_test


release:
  extends: .release
  secrets:
    GITLAB_TOKEN:
      vault: mobile_chapter/time/protected/semantic_release/gitlab_token@youniqx
      file: false


Build Dmg:
  tags: [macos, current-xc]
  stage: build
  rules:
    - if: $CI_COMMIT_REF_PROTECTED != "true"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
  script:
    - ./scripts/build.sh --dmg
  artifacts:
    paths:
      - time-*.dmg
    expire_in: 24 hours


Build Linux AppImage:
  tags: [linux-unprivileged]
  image: harbor.youniqx.com/youniqx-cloud-infrastructure/youniqx/mia/android-build:1.14.6
  variables:
    KUBERNETES_MEMORY_REQUEST: 20Gi
    KUBERNETES_MEMORY_LIMIT: 20Gi
  stage: build
  rules:
    - if: $CI_COMMIT_REF_PROTECTED != "true"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
  script:
    - ./scripts/build.sh --appImage
  artifacts:
    paths:
      - time-*.AppImage
    expire_in: 24 hours


Upload Binaries:
  tags: [linux-unprivileged]
  image: harbor.youniqx.com/youniqx-cloud-infrastructure/youniqx/infrastructure/youniqx-ubuntu:1.8.101
  stage: build
  needs:
    - job: "Build Linux AppImage"
    - job: "Build Dmg"
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  extends: .vault
  secrets:
    GITLAB_TOKEN:
      vault: mobile_chapter/time/protected/semantic_release/gitlab_token@youniqx
      file: false
  script:
    - ./scripts/upload.sh
