package com.youniqx.time.theme

import androidx.compose.ui.graphics.Color

// Timer-specific colors (used across themes)
val TimerActiveColor = Color(0xFF38B2AC)      // Teal when running
val TimerPausedColor = Color(0xFFF6AD55)      // Amber when paused
val TimerIdleColor = Color(0xFFA0AEC0)        // Gray when idle

// Modern Minimal Light Theme - Slate/Teal palette
val primaryLight = Color(0xFF2D3748)          // Slate gray - professional
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE2E8F0)
val onPrimaryContainerLight = Color(0xFF1A202C)
val secondaryLight = Color(0xFF4A5568)        // Cool gray
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEDF2F7)
val onSecondaryContainerLight = Color(0xFF2D3748)
val tertiaryLight = Color(0xFF319795)         // Teal accent
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB2F5EA)
val onTertiaryContainerLight = Color(0xFF234E52)
val errorLight = Color(0xFFE53E3E)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFED7D7)
val onErrorContainerLight = Color(0xFF742A2A)
val backgroundLight = Color(0xFFF7FAFC)       // Subtle gray background
val onBackgroundLight = Color(0xFF1A202C)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1A202C)
val surfaceVariantLight = Color(0xFFF7FAFC)
val onSurfaceVariantLight = Color(0xFF4A5568)
val outlineLight = Color(0xFFE2E8F0)          // Very subtle borders
val outlineVariantLight = Color(0xFFCBD5E1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3748)
val inverseOnSurfaceLight = Color(0xFFF7FAFC)
val inversePrimaryLight = Color(0xFF90CDF4)
val surfaceDimLight = Color(0xFFEDF2F7)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7FAFC)
val surfaceContainerLight = Color(0xFFF1F5F9)
val surfaceContainerHighLight = Color(0xFFEDF2F7)
val surfaceContainerHighestLight = Color(0xFFE2E8F0)

// Medium contrast light - Slightly bolder slate
val primaryLightMediumContrast = Color(0xFF1A202C)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF4A5568)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2D3748)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF718096)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF234E52)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF2C7A7B)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF9B2C2C)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFC53030)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF7FAFC)
val onBackgroundLightMediumContrast = Color(0xFF1A202C)
val surfaceLightMediumContrast = Color(0xFFFFFFFF)
val onSurfaceLightMediumContrast = Color(0xFF1A202C)
val surfaceVariantLightMediumContrast = Color(0xFFF7FAFC)
val onSurfaceVariantLightMediumContrast = Color(0xFF2D3748)
val outlineLightMediumContrast = Color(0xFF4A5568)
val outlineVariantLightMediumContrast = Color(0xFF718096)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D3748)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF7FAFC)
val inversePrimaryLightMediumContrast = Color(0xFF90CDF4)
val surfaceDimLightMediumContrast = Color(0xFFEDF2F7)
val surfaceBrightLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF7FAFC)
val surfaceContainerLightMediumContrast = Color(0xFFF1F5F9)
val surfaceContainerHighLightMediumContrast = Color(0xFFEDF2F7)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE2E8F0)

// High contrast light - Maximum contrast slate
val primaryLightHighContrast = Color(0xFF0D1117)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF1A202C)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF171923)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2D3748)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF1D4044)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF234E52)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF742A2A)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF9B2C2C)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF7FAFC)
val onBackgroundLightHighContrast = Color(0xFF1A202C)
val surfaceLightHighContrast = Color(0xFFFFFFFF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF7FAFC)
val onSurfaceVariantLightHighContrast = Color(0xFF1A202C)
val outlineLightHighContrast = Color(0xFF2D3748)
val outlineVariantLightHighContrast = Color(0xFF2D3748)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF1A202C)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFBEE3F8)
val surfaceDimLightHighContrast = Color(0xFFEDF2F7)
val surfaceBrightLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF7FAFC)
val surfaceContainerLightHighContrast = Color(0xFFF1F5F9)
val surfaceContainerHighLightHighContrast = Color(0xFFEDF2F7)
val surfaceContainerHighestLightHighContrast = Color(0xFFE2E8F0)

// Modern Minimal Dark Theme - Slate/Teal palette
val primaryDark = Color(0xFFE2E8F0)           // Light slate for dark mode
val onPrimaryDark = Color(0xFF1A202C)
val primaryContainerDark = Color(0xFF2D3748)
val onPrimaryContainerDark = Color(0xFFE2E8F0)
val secondaryDark = Color(0xFFA0AEC0)         // Muted slate
val onSecondaryDark = Color(0xFF1A202C)
val secondaryContainerDark = Color(0xFF4A5568)
val onSecondaryContainerDark = Color(0xFFE2E8F0)
val tertiaryDark = Color(0xFF81E6D9)          // Bright teal for dark mode
val onTertiaryDark = Color(0xFF1D4044)
val tertiaryContainerDark = Color(0xFF285E61)
val onTertiaryContainerDark = Color(0xFFB2F5EA)
val errorDark = Color(0xFFFEB2B2)
val onErrorDark = Color(0xFF742A2A)
val errorContainerDark = Color(0xFF9B2C2C)
val onErrorContainerDark = Color(0xFFFED7D7)
val backgroundDark = Color(0xFF0D1117)        // Very dark background
val onBackgroundDark = Color(0xFFE2E8F0)
val surfaceDark = Color(0xFF161B22)           // Slightly lighter surface
val onSurfaceDark = Color(0xFFE2E8F0)
val surfaceVariantDark = Color(0xFF21262D)
val onSurfaceVariantDark = Color(0xFFA0AEC0)
val outlineDark = Color(0xFF4A5568)
val outlineVariantDark = Color(0xFF2D3748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E8F0)
val inverseOnSurfaceDark = Color(0xFF1A202C)
val inversePrimaryDark = Color(0xFF2D3748)
val surfaceDimDark = Color(0xFF0D1117)
val surfaceBrightDark = Color(0xFF2D3748)
val surfaceContainerLowestDark = Color(0xFF010409)
val surfaceContainerLowDark = Color(0xFF0D1117)
val surfaceContainerDark = Color(0xFF161B22)
val surfaceContainerHighDark = Color(0xFF21262D)
val surfaceContainerHighestDark = Color(0xFF2D3748)

// Medium contrast dark - Slightly lighter
val primaryDarkMediumContrast = Color(0xFFF7FAFC)
val onPrimaryDarkMediumContrast = Color(0xFF0D1117)
val primaryContainerDarkMediumContrast = Color(0xFFA0AEC0)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCBD5E1)
val onSecondaryDarkMediumContrast = Color(0xFF0D1117)
val secondaryContainerDarkMediumContrast = Color(0xFF718096)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF9AE6B4)
val onTertiaryDarkMediumContrast = Color(0xFF0D1117)
val tertiaryContainerDarkMediumContrast = Color(0xFF38A169)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFED7D7)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFC8181)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0D1117)
val onBackgroundDarkMediumContrast = Color(0xFFE2E8F0)
val surfaceDarkMediumContrast = Color(0xFF161B22)
val onSurfaceDarkMediumContrast = Color(0xFFF7FAFC)
val surfaceVariantDarkMediumContrast = Color(0xFF21262D)
val onSurfaceVariantDarkMediumContrast = Color(0xFFCBD5E1)
val outlineDarkMediumContrast = Color(0xFFA0AEC0)
val outlineVariantDarkMediumContrast = Color(0xFF718096)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E8F0)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF21262D)
val inversePrimaryDarkMediumContrast = Color(0xFF1A202C)
val surfaceDimDarkMediumContrast = Color(0xFF0D1117)
val surfaceBrightDarkMediumContrast = Color(0xFF2D3748)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF010409)
val surfaceContainerLowDarkMediumContrast = Color(0xFF0D1117)
val surfaceContainerDarkMediumContrast = Color(0xFF161B22)
val surfaceContainerHighDarkMediumContrast = Color(0xFF21262D)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF2D3748)

// High contrast dark - Maximum contrast
val primaryDarkHighContrast = Color(0xFFFFFFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFF7FAFC)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFCBD5E1)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFFFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9AE6B4)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFFFFF)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFED7D7)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0D1117)
val onBackgroundDarkHighContrast = Color(0xFFE2E8F0)
val surfaceDarkHighContrast = Color(0xFF0D1117)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF21262D)
val onSurfaceVariantDarkHighContrast = Color(0xFFF7FAFC)
val outlineDarkHighContrast = Color(0xFFCBD5E1)
val outlineVariantDarkHighContrast = Color(0xFFCBD5E1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E8F0)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF0D1117)
val surfaceDimDarkHighContrast = Color(0xFF0D1117)
val surfaceBrightDarkHighContrast = Color(0xFF2D3748)
val surfaceContainerLowestDarkHighContrast = Color(0xFF010409)
val surfaceContainerLowDarkHighContrast = Color(0xFF0D1117)
val surfaceContainerDarkHighContrast = Color(0xFF161B22)
val surfaceContainerHighDarkHighContrast = Color(0xFF21262D)
val surfaceContainerHighestDarkHighContrast = Color(0xFF2D3748)







