name: Deploy Release to Pages

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download Release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download ${{ github.event.release.tag_name }} --pattern 'time*-web.tar.gz'
          tar -zxf time*-web.tar.gz
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './public'
      - name: Deploy to GitHub
        id: deployment
        uses: actions/deploy-pages@v5
